#### Basic analysis parameters ####
analysisMode: 'TN'  # TN, TO, germline, de_novo
callers:            # available callers: svaba, breakdancer, delly, manta
- svaba
- breakdancer
- delly
- manta
runMode:
  callAndAnnotate: no
  callOnly: no
  annotateOnly: yes
refGenome: '/DCEG/CGF/Bioinformatics/Production/Bari/refGenomes/hg19_canonical_correct_chr_order.fa'
genomeBuild: 'hg19'  # hg19 (chr) or b37 (no chr)


#### Annotation parameters ####
annotateFile: '/DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/snake_tests/chr5_list_output_test/SV_files_for_annotation.txt'
annotationParams:
  interchromPadding: 50
  insertionPadding: 500
  crossCallerOverlap: 0.7
  genomicContextOverlap: 0.7
  publicDataOverlap: 0.7


#### Samples to analyze ####
inFile: '/DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/snake_tests/test_input/tests_chr5bams.txt'  # for testing TN
  # must contain three columns: sample name, tumor bam, normal bam (space-delimited)
  # or, if de novo, must contain family ID, parent1 bam, parent2 bam, child bam
  # or, if germline, must contain sample name and bam
  # or, if tumor-only, must contain tumor bam...and PON?
  # ALSO, if the callers available have differing capabilities, be sure to have a check in the snakefile (e.g. if delly can't do tumor-only, check for delly=yes and react appropriately in the TO snakefile)


#### Directories ####
inDir: '/DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/snake_tests/test_input'
execDir: '/DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/pipeline_dev'  # where the snakefiles are
outDir: '/DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/pipeline_dev/test_out'
logDir: '/DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/pipeline_dev/test_out/logs'
tempDir: '/ttemp/ballewbj/sv'


#### Cluster parameters ####
clusterMode: 'qsub -V -S /bin/sh -q long.q -o /DCEG/CGF/Bioinformatics/Production/Bari/Struct_var_pipeline_dev/pipeline_dev/test_out/logs -j y'
maxNumJobs: 8
maxThreads:
- 4
- 1
- 1
- 4


#### Caller-specific parameters ####
# Consider adding a user-configurable command line for each caller?

